#!/usr/bin/env perl

use strict;
use warnings;

use File::Find;
use File::Basename;
use File::Spec;
use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/lib" }

my $import = "Gion::Batch::";

# 無指定であればpm一覧を返す
unless (defined $ARGV[0]){
    my @dirpath = split /::/, $import;
    find(\&pmfile,File::Spec->catdir(
        $FindBin::Bin, 'lib', @dirpath));
    exit;
}else{
    $import .= ucfirst(shift);
}

eval "require $import";
die $@ if $@;

my $class = $import->new;
$class->run(@ARGV);

sub pmfile {
    my $fn = File::Basename::basename($File::Find::name);
    return unless $fn =~ /\.pm$/;
    $fn =~ s/\.pm$//;
    print lc($fn) . "\n";
}
